name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build and test infc
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: balances_contract
    steps:
      - name: Setup Rust
        uses: actions/checkout@v4.1.3
      - name: Update Rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Install clippy nightly
        run: rustup component add clippy-preview
      - name: Install Cargo audit
        run: cargo install cargo-audit
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
      - name: Clippy
        run: cargo clippy --verbose -- -D warnings
